#!/usr/bin/env node
/* Build the self-hosted font set.
 *
 *   node tools/build-fonts.js
 *
 * Why self-hosted at all: the footer promises nothing is tracking you, but
 * Google Fonts hands the reader's IP to Google on every visit, and the
 * render-blocking round-trip to fonts.googleapis.com cost ~380ms of first paint.
 *
 * Two deliberate choices:
 *  - Inter / JetBrains Mono / Noto Georgian are pulled as VARIABLE fonts: one
 *    file per subset covers every weight (Inter alone: 380KB of static weights
 *    -> 130KB).
 *  - Fraunces stays STATIC, exactly as Google served it. It sets the hero
 *    wordmark, and its variable build carries an optical-size axis that would
 *    subtly restyle that title. Not worth it for a few KB.
 *
 * Only the subsets this guide can actually render are kept: latin, latin-ext
 * (Czech/Slovene/German diacritics) and georgian. unicode-range is preserved,
 * so an English reader never downloads a Georgian face.
 */
const fs = require('fs');
const path = require('path');
const https = require('https');

const OUT_DIR = path.join(__dirname, '..', 'assets', 'fonts');
const OUT_CSS = path.join(__dirname, '..', 'assets', 'fonts.css');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36';

/* Weights the stylesheet actually uses are 400/500/600 plus 700 for <strong>.
   300 was requested for years and never used once. */
const SOURCES = [
  { css: 'family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700', keepSubsets: ['latin', 'latin-ext'] },
  { css: 'family=Inter:wght@400..700', keepSubsets: ['latin', 'latin-ext'] },
  { css: 'family=JetBrains+Mono:wght@400..500', keepSubsets: ['latin', 'latin-ext'] },
  // The Georgian faces sit behind the latin families in every stack, so their
  // latin subsets are unreachable — georgian only.
  { css: 'family=Noto+Serif+Georgian:wght@400..700', keepSubsets: ['georgian'] },
  { css: 'family=Noto+Sans+Georgian:wght@400..600', keepSubsets: ['georgian'] },
];

const get = (url, binary) =>
  new Promise((resolve, reject) => {
    https
      .get(url, { headers: { 'User-Agent': UA } }, (res) => {
        if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} for ${url}`));
        const chunks = [];
        res.on('data', (d) => chunks.push(d));
        res.on('end', () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString('utf8')));
      })
      .on('error', reject);
  });

const slug = (s) => s.toLowerCase().replace(/\s+/g, '-');

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const f of fs.readdirSync(OUT_DIR)) fs.unlinkSync(path.join(OUT_DIR, f)); // rebuild from scratch

  let out = `/* GENERATED by tools/build-fonts.js — do not edit by hand.
   Self-hosted so the page never calls out to Google (see the footer promise)
   and so first paint isn't blocked on a third-party round-trip. */\n\n`;
  let total = 0;
  let files = 0;

  for (const src of SOURCES) {
    const css = await get(`https://fonts.googleapis.com/css2?${src.css}&display=swap`, false);
    const re = /\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g;
    let m;
    while ((m = re.exec(css))) {
      const [, subset, block] = m;
      if (!src.keepSubsets.includes(subset)) continue;
      const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
      const weight = (block.match(/font-weight:\s*([^;]+);/) || [])[1].trim().replace(/\s+/g, '-');
      const style = (block.match(/font-style:\s*([^;]+);/) || [])[1].trim();
      const url = (block.match(/url\(([^)]+)\)/) || [])[1];

      const name = `${slug(family)}-${subset}-${weight}-${style}.woff2`;
      const buf = await get(url, true);
      fs.writeFileSync(path.join(OUT_DIR, name), buf);
      total += buf.length;
      files++;

      out +=
        block
          .replace(/url\([^)]+\)/, `url(fonts/${name})`)
          .replace(/\s+/g, ' ')
          .replace(/\{ /, '{\n  ')
          .replace(/; /g, ';\n  ')
          .replace(/ \}/, '\n}') + '\n\n';
    }
  }

  fs.writeFileSync(OUT_CSS, out);
  console.log(`✓ ${files} woff2 files, ${(total / 1024).toFixed(0)} KB on disk`);
  console.log(`✓ wrote assets/fonts.css`);
})();
